version: '3'

services:
  mysql:
    build: ./mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  flask:
    build: ./flask
    ports:
      - "5000:5000"
    links:
      - mysql:mysql

